### ISSUE TITLE
The plugin is incompatible with the path url strategy

### ISSUE THREAD

**Issue by OrionWambert** [enjkvbej/navigator_manager#2]
I want to use this plugin to manage the navigation and routing of my application except that when I use as strategy le path the navigation and routing does not work anymore here is an example of code to change strategy

```
 if(kIsWeb){
    setUrlStrategy(PathUrlStrategy());
  }
```

**Comment by enjkvbej** [comment]
Thank you for your issue. I will fix it soon.

**Comment by enjkvbej** [comment]
@OrionWambert hi，I solve the problem like this. It works for me in chrome.
your pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
```
your main.dart
```
import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void main() {
  setUrlStrategy(PathUrlStrategy());
  runApp(MyApp());
}
```
